version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    volumes:
      - ./app:/app/app  # Monta apenas a pasta "app" local em /app/app do container
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  frontend:
    build:
      context: ./insumo-track-frontend
      args:
        - VITE_API_URL=/api  # Define a URL relativa para as chamadas à API
    container_name: frontend
    ports:
      - "80:80"  # Em produção, geralmente o Nginx escuta na porta 80
    environment:
      - VITE_API_URL=/api
    depends_on:
      backend:
        condition: service_healthy
    restart: always
