services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: backend
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: always

  frontend:
    build:
      context: ./insumo-track-frontend
      args:
        - VITE_API_URL=http://localhost:8000
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always
