# Fase 1: Construção do frontend com Node.js
FROM node:18 AS build

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos do frontend
COPY package.json package-lock.json ./
RUN npm install

# Copia todo o código do frontend para o container
COPY . .

# Define a variável antes do build
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

# Build do frontend com Vite
RUN npm run build

# Fase 2: Servir os arquivos estáticos com Nginx
FROM nginx:alpine

# Copia o arquivo de configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos do build (dist/) para o Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Expor a porta 80 para servir o frontend
EXPOSE 80

# Comando para rodar o Nginx
CMD ["nginx", "-g", "daemon off;"]
