"""atualizar tabela baixa item requisicao

Revision ID: 377ab32b59a1
Revises: ecb556e0ecdf
Create Date: 2025-02-21 16:42:31.130645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377ab32b59a1'
down_revision: Union[str, None] = 'ecb556e0ecdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
