"""adicionar campo observação tabela historico aprovacao

Revision ID: acb70399f714
Revises: bdcf18bda823
Create Date: 2025-02-13 11:34:43.674530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb70399f714'
down_revision: Union[str, None] = 'bdcf18bda823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_status_requisicao', sa.Column('observacao_aprovacao', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historico_status_requisicao', 'observacao_aprovacao')
    # ### end Alembic commands ###
