"""criação tables

Revision ID: 3054766edbb7
Revises: 
Create Date: 2025-02-11 10:39:28.547210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3054766edbb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo_empresa', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('obras',
    sa.Column('codigo_projeto', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_projeto'),
    sa.UniqueConstraint('codigo_projeto')
    )
    op.create_table('status_requisicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_status', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_status'),
    sa.UniqueConstraint('descricao')
    )
    op.create_index(op.f('ix_status_requisicao_id'), 'status_requisicao', ['id'], unique=False)
    op.create_table('gerencial_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_fechamento', sa.Date(), nullable=False),
    sa.Column('codigo_projeto', sa.String(length=50), nullable=False),
    sa.Column('obra', sa.String(length=255), nullable=False),
    sa.Column('codigo_estruturado', sa.String(length=50), nullable=False),
    sa.Column('grupo', sa.String(length=255), nullable=False),
    sa.Column('subgrupo_1', sa.String(length=255), nullable=False),
    sa.Column('subgrupo_2', sa.String(length=255), nullable=False),
    sa.Column('subgrupo_3', sa.String(length=255), nullable=False),
    sa.Column('servico', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('orcamento_inicial_qtd', sa.Float(), nullable=False),
    sa.Column('orcamento_inicial_valor', sa.Float(), nullable=False),
    sa.Column('tendencia_anterior_qtd', sa.Float(), nullable=False),
    sa.Column('tendencia_anterior_valor', sa.Float(), nullable=False),
    sa.Column('tendencia_atual_qtd', sa.Float(), nullable=False),
    sa.Column('tendencia_atual_valor', sa.Float(), nullable=False),
    sa.Column('tendencia_atual_x_anterior', sa.Float(), nullable=False),
    sa.Column('realizado_periodo_qtd', sa.Float(), nullable=False),
    sa.Column('realizado_periodo_valor', sa.Float(), nullable=False),
    sa.Column('realizado_acumulado_qtd', sa.Float(), nullable=False),
    sa.Column('realizado_acumulado_valor', sa.Float(), nullable=False),
    sa.Column('ordem_compra_qtd', sa.Float(), nullable=False),
    sa.Column('ordem_compra_valor', sa.Float(), nullable=False),
    sa.Column('saldo_contrato_qtd', sa.Float(), nullable=False),
    sa.Column('saldo_contrato_valor', sa.Float(), nullable=False),
    sa.Column('projecao_qtd', sa.Float(), nullable=False),
    sa.Column('projecao_valor', sa.Float(), nullable=False),
    sa.Column('evolucao_fisica', sa.Float(), nullable=False),
    sa.Column('a_gastar_qtd', sa.Float(), nullable=False),
    sa.Column('a_gastar_valor', sa.Float(), nullable=False),
    sa.Column('tipo_projecao', sa.String(length=50), nullable=False),
    sa.Column('desvio_qtd', sa.Float(), nullable=False),
    sa.Column('desvio_valor', sa.Float(), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['codigo_projeto'], ['obras.codigo_projeto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gerencial_obra_id'), 'gerencial_obra', ['id'], unique=False)
    op.create_table('locais_aplicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo_projeto', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_projeto'], ['obras.codigo_projeto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locais_aplicacao_id'), 'locais_aplicacao', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('codigo_projeto', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_projeto'], ['obras.codigo_projeto'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('requisicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_aprovador_id', sa.Integer(), nullable=True),
    sa.Column('codigo_projeto', sa.String(length=50), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_projeto'], ['obras.codigo_projeto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['status_requisicao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_aprovador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisicoes_id'), 'requisicoes', ['id'], unique=False)
    op.create_table('historico_status_requisicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisicao_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requisicao_id'], ['requisicoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['status_requisicao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_status_requisicao_id'), 'historico_status_requisicao', ['id'], unique=False)
    op.create_table('itens_requisicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisicao_id', sa.Integer(), nullable=True),
    sa.Column('subgrupo_1', sa.String(length=255), nullable=False),
    sa.Column('subgrupo_2', sa.String(length=255), nullable=False),
    sa.Column('subgrupo_3', sa.String(length=255), nullable=False),
    sa.Column('servico', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('quantidade_requisitada', sa.Float(), nullable=False),
    sa.Column('local_aplicacao', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['requisicao_id'], ['requisicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_requisicao_id'), 'itens_requisicao', ['id'], unique=False)
    op.create_table('baixas_itens_requisicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_requisicao_id', sa.Integer(), nullable=True),
    sa.Column('usuario_baixa_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_baixada', sa.Float(), nullable=False),
    sa.Column('data_baixa', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_requisicao_id'], ['itens_requisicao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_baixa_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baixas_itens_requisicao_id'), 'baixas_itens_requisicao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baixas_itens_requisicao_id'), table_name='baixas_itens_requisicao')
    op.drop_table('baixas_itens_requisicao')
    op.drop_index(op.f('ix_itens_requisicao_id'), table_name='itens_requisicao')
    op.drop_table('itens_requisicao')
    op.drop_index(op.f('ix_historico_status_requisicao_id'), table_name='historico_status_requisicao')
    op.drop_table('historico_status_requisicao')
    op.drop_index(op.f('ix_requisicoes_id'), table_name='requisicoes')
    op.drop_table('requisicoes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_locais_aplicacao_id'), table_name='locais_aplicacao')
    op.drop_table('locais_aplicacao')
    op.drop_index(op.f('ix_gerencial_obra_id'), table_name='gerencial_obra')
    op.drop_table('gerencial_obra')
    op.drop_index(op.f('ix_status_requisicao_id'), table_name='status_requisicao')
    op.drop_table('status_requisicao')
    op.drop_table('obras')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
