"""adicionar coluna programacao subida em tabela requisicoes

Revision ID: d3b1c3f35103
Revises: 9d093528e0d6
Create Date: 2025-02-18 14:25:32.066789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b1c3f35103'
down_revision: Union[str, None] = '9d093528e0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baixas_itens_requisicao', 'item_requisicao_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('baixas_itens_requisicao', 'usuario_baixa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'baixas_itens_requisicao', 'requisicoes', ['requisicao_id'], ['id'], ondelete='CASCADE')
    op.add_column('requisicoes', sa.Column('data_programacao_subida', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisicoes', 'data_programacao_subida')
    op.drop_constraint(None, 'baixas_itens_requisicao', type_='foreignkey')
    op.alter_column('baixas_itens_requisicao', 'usuario_baixa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('baixas_itens_requisicao', 'item_requisicao_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
