"""fix

Revision ID: ea93823f46c5
Revises: 3054766edbb7
Create Date: 2025-02-11 11:34:06.594823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea93823f46c5'
down_revision: Union[str, None] = '3054766edbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'obras', ['codigo_projeto'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'obras', type_='unique')
    # ### end Alembic commands ###
