"""nova tabela unidades

Revision ID: ecb556e0ecdf
Revises: d3b1c3f35103
Create Date: 2025-02-21 14:40:43.885771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb556e0ecdf'
down_revision: Union[str, None] = 'd3b1c3f35103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidades_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_index(op.f('ix_unidades_medida_id'), 'unidades_medida', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unidades_medida_id'), table_name='unidades_medida')
    op.drop_table('unidades_medida')
    # ### end Alembic commands ###
