# Usa a imagem oficial do Python
FROM python:3.11

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos do backend para dentro do container
COPY . /app

# Instala as dependências
RUN pip install --no-cache-dir -r app/requirements.txt

# Comando padrão para rodar a aplicação
CMD ["python", "main.py"]
